// @ts-nocheck
import DocumentList from '@/views/DocumentList.vue'
import GitHistory from '@/components/GitHistory.vue'
import DatasetsUtils from '@/assets/DatasetsUtils'
import Utils from '@/assets/Utils'
import {afterEach, beforeEach, describe, expect, jest, test} from '@jest/globals'
import {shallowMount} from '@vue/test-utils'
import axios from 'axios'
import _ from 'lodash'
import {ACLProfile, Branch, Commit, ContentFilterProfile, Document} from '@/types'
import {FlowControlPolicy, GlobalFilter, RateLimit, SecurityPolicy} from '@/types'
import {setImmediate, setTimeout} from 'timers'
import {DOMWrapper} from '@vue/test-utils'