name: Run Build/Push Dev Images
on:
  workflow_dispatch:

jobs:
  Build-Images:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build image
        uses: ./.github/actions/build/image/
        with:
          GCP_PROJECT_ID:         "${{ secrets.GCP_PROJECT_ID }}"
          GCP_SA_KEY:             "${{ secrets.GCP_SA_KEY }}"
          GH_ENV:                 "dev"
          REGION:                 "eu-central-1"
