name: Run Deploy UI To GCS
on:
  workflow_dispatch:
    inputs:
      GH_ENV:
        description: 'Environment:'
        required: true
        type: choice
        options:
        - dev
        default: 'dev'

jobs:
  Print-Inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        working-directory: ./
        run: |
          echo -e "\nPrinting Input:"
          echo "GH_ENV:                ${{ github.event.inputs.GH_ENV }}"
          
  Build-And-Upload:  
    environment: ${{ github.event.inputs.GH_ENV }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up GCP
        uses: google-github-actions/auth@v0.4.3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: |-
          npm install
          npm run build
      - name: Deploy-To-GCS
        run: |-
          echo "using bucket rbz${{ github.event.inputs.GH_ENV }}uiv5"
          ls -alh
          gsutil -m -h "Cache-Control:no-cache,max-age=0" rsync -d -r dist "gs://rbz${{ github.event.inputs.GH_ENV }}uiv5"
